services:
  terraform:
    image: hashicorp/terraform:1.16.4
    working_dir: /work
    volumes:
      - .:/work
    environment:
      TF_IN_AUTOMATION: "true"
    networks:
      - sandbox

  kumo:
    image: ghcr.io/sivchari/kumo:0.28.1
    environment:
      KUMO_DATA_DIR: /data
    volumes:
      - kumo-data:/data
    ports:
      - "127.0.0.1:4566:4566"
    networks:
      - sandbox

networks:
  sandbox:

volumes:
  kumo-data:
